clc;
clear;

%% caculate standatd faces and adjacency matrix
sphere_163842 = mvtk_read('/media/fenqiang/DATA/unc/Data/registration/scripts/neigh_indices/sphere_163842_rotated_0.vtk');
faces = sphere_163842.faces;
pts = sphere_163842.vertices;


%% rotate 90 degree along y axis

rotate_mat = [cos(pi/2), 0, sin(pi/2)
              0, 1, 0
             -sin(pi/2), 0, cos(pi/2)];
rotated_pts = rotate_mat * transpose(pts);
rotated_pts = transpose(rotated_pts);

rotated_surface = struct('vertices',rotated_pts, ...
                  'faces', faces, ...
                  'curv', sphere_163842.curv, ...
                  'sulc', sphere_163842.sulc);
mvtk_write(rotated_surface, '/media/fenqiang/DATA/unc/Data/registration/scripts/neigh_indices/sphere_163842_rotated_1.vtk', 'legacy-ascii');

template = mvtk_read('/media/fenqiang/DATA/unc/Data/registration/scripts/neigh_indices/sphere_40962_rotated_0.vtk');
rotated_surface_40962 = struct('vertices',rotated_pts(1:40962,:), ...
                              'faces', template.faces, ...
                              'thickness', template.thickness(1:40962,:));              
mvtk_write(rotated_surface_40962, '/media/fenqiang/DATA/unc/Data/registration/scripts/neigh_indices/sphere_40962_rotated_1.vtk', 'legacy-ascii');

template = mvtk_read('/media/fenqiang/DATA/unc/Data/registration/scripts/neigh_indices/sphere_10242_rotated_0.vtk');
rotated_surface_10242 = struct('vertices',rotated_pts(1:10242,:), ...
                              'faces', template.faces, ...
                              'curv', template.curv(1:10242,:), ...
                              'sulc', template.sulc(1:10242,:));              
mvtk_write(rotated_surface_10242, '/media/fenqiang/DATA/unc/Data/registration/scripts/neigh_indices/sphere_10242_rotated_1.vtk', 'legacy-ascii');

template = mvtk_read('/media/fenqiang/DATA/unc/Data/registration/scripts/neigh_indices/sphere_2562_rotated_0.vtk');
rotated_surface_2562 = struct('vertices',rotated_pts(1:2562,:), ...
                              'faces', template.faces, ...
                              'curv', template.curv(1:2562,:), ...
                              'sulc', template.sulc(1:2562,:));              
mvtk_write(rotated_surface_2562, '/media/fenqiang/DATA/unc/Data/registration/scripts/neigh_indices/sphere_2562_rotated_1.vtk', 'legacy-ascii');

template = mvtk_read('/media/fenqiang/DATA/unc/Data/registration/scripts/neigh_indices/sphere_642_rotated_0.vtk');
rotated_surface_642 = struct('vertices',rotated_pts(1:642,:), ...
                              'faces', template.faces, ...
                              'curv', template.curv(1:642,:), ...
                              'sulc', template.sulc(1:642,:));              
mvtk_write(rotated_surface_642, '/media/fenqiang/DATA/unc/Data/registration/scripts/neigh_indices/sphere_642_rotated_1.vtk', 'legacy-ascii');

template = mvtk_read('/media/fenqiang/DATA/unc/Data/registration/scripts/neigh_indices/sphere_162_rotated_0.vtk');
rotated_surface_162 = struct('vertices',rotated_pts(1:162,:), ...
                              'faces', template.faces, ...
                              'curv', template.curv(1:162,:), ...
                              'sulc', template.sulc(1:162,:));              
mvtk_write(rotated_surface_162, '/media/fenqiang/DATA/unc/Data/registration/scripts/neigh_indices/sphere_162_rotated_1.vtk', 'legacy-ascii');

template = mvtk_read('/media/fenqiang/DATA/unc/Data/registration/scripts/neigh_indices/sphere_42_rotated_0.vtk');
rotated_surface_42 = struct('vertices',rotated_pts(1:42,:), ...
                              'faces', template.faces, ...
                              'curv', template.curv(1:42,:), ...
                              'sulc', template.sulc(1:42,:));              
mvtk_write(rotated_surface_42, '/media/fenqiang/DATA/unc/Data/registration/scripts/neigh_indices/sphere_42_rotated_1.vtk', 'legacy-ascii');

template = mvtk_read('/media/fenqiang/DATA/unc/Data/registration/scripts/neigh_indices/sphere_12_rotated_0.vtk');
rotated_surface_12 = struct('vertices',rotated_pts(1:12,:), ...
                              'faces', template.faces, ...
                              'curv', template.curv(1:12,:));              
mvtk_write(rotated_surface_12, '/media/fenqiang/DATA/unc/Data/registration/scripts/neigh_indices/sphere_12_rotated_1.vtk', 'legacy-ascii');



%% rotate 90 degree along y axis

rotate_mat = [1, 0, 0
              0, cos(pi/2), -sin(pi/2)
              0, sin(pi/2), cos(pi/2)];
rotated_pts = rotate_mat * transpose(rotated_pts);
rotated_pts = transpose(rotated_pts);

rotated_surface = struct('vertices',rotated_pts, ...
                  'faces', faces, ...
                  'curv', sphere_163842.curv, ...
                  'sulc', sphere_163842.sulc);
                           
mvtk_write(rotated_surface, '/media/fenqiang/DATA/unc/Data/Template/sphere_163842_rotated_2.vtk', 'legacy-ascii');


template = mvtk_read('/media/fenqiang/DATA/unc/Data/registration/scripts/neigh_indices/sphere_40962_rotated_0.vtk');
rotated_surface_40962 = struct('vertices',rotated_pts(1:40962,:), ...
                              'faces', template.faces, ...
                              'thickness', template.thickness(1:40962,:));              
mvtk_write(rotated_surface_40962, '/media/fenqiang/DATA/unc/Data/registration/scripts/neigh_indices/sphere_40962_rotated_2.vtk', 'legacy-ascii');

template = mvtk_read('/media/fenqiang/DATA/unc/Data/registration/scripts/neigh_indices/sphere_10242_rotated_0.vtk');
rotated_surface_10242 = struct('vertices',rotated_pts(1:10242,:), ...
                              'faces', template.faces, ...
                              'curv', template.curv(1:10242,:), ...
                              'sulc', template.sulc(1:10242,:));              
mvtk_write(rotated_surface_10242, '/media/fenqiang/DATA/unc/Data/registration/scripts/neigh_indices/sphere_10242_rotated_2.vtk', 'legacy-ascii');

template = mvtk_read('/media/fenqiang/DATA/unc/Data/registration/scripts/neigh_indices/sphere_2562_rotated_0.vtk');
rotated_surface_2562 = struct('vertices',rotated_pts(1:2562,:), ...
                              'faces', template.faces, ...
                              'curv', template.curv(1:2562,:), ...
                              'sulc', template.sulc(1:2562,:));              
mvtk_write(rotated_surface_2562, '/media/fenqiang/DATA/unc/Data/registration/scripts/neigh_indices/sphere_2562_rotated_2.vtk', 'legacy-ascii');

template = mvtk_read('/media/fenqiang/DATA/unc/Data/registration/scripts/neigh_indices/sphere_642_rotated_0.vtk');
rotated_surface_642 = struct('vertices',rotated_pts(1:642,:), ...
                              'faces', template.faces, ...
                              'curv', template.curv(1:642,:), ...
                              'sulc', template.sulc(1:642,:));              
mvtk_write(rotated_surface_642, '/media/fenqiang/DATA/unc/Data/registration/scripts/neigh_indices/sphere_642_rotated_2.vtk', 'legacy-ascii');

template = mvtk_read('/media/fenqiang/DATA/unc/Data/registration/scripts/neigh_indices/sphere_162_rotated_0.vtk');
rotated_surface_162 = struct('vertices',rotated_pts(1:162,:), ...
                              'faces', template.faces, ...
                              'curv', template.curv(1:162,:), ...
                              'sulc', template.sulc(1:162,:));              
mvtk_write(rotated_surface_162, '/media/fenqiang/DATA/unc/Data/registration/scripts/neigh_indices/sphere_162_rotated_2.vtk', 'legacy-ascii');

template = mvtk_read('/media/fenqiang/DATA/unc/Data/registration/scripts/neigh_indices/sphere_42_rotated_0.vtk');
rotated_surface_42 = struct('vertices',rotated_pts(1:42,:), ...
                              'faces', template.faces, ...
                              'curv', template.curv(1:42,:), ...
                              'sulc', template.sulc(1:42,:));              
mvtk_write(rotated_surface_42, '/media/fenqiang/DATA/unc/Data/registration/scripts/neigh_indices/sphere_42_rotated_2.vtk', 'legacy-ascii');

template = mvtk_read('/media/fenqiang/DATA/unc/Data/registration/scripts/neigh_indices/sphere_12_rotated_0.vtk');
rotated_surface_12 = struct('vertices',rotated_pts(1:12,:), ...
                              'faces', template.faces, ...
                              'curv', template.curv(1:12,:));              
mvtk_write(rotated_surface_12, '/media/fenqiang/DATA/unc/Data/registration/scripts/neigh_indices/sphere_12_rotated_2.vtk', 'legacy-ascii');


